version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10.17.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
      - run:
          name: AWS EC2 deploy
          command: ssh -o StrictHostKeyChecking=no ec2-user@$EC2IP "/var/www/$PROJECT_FOLDER/www/deploy.sh"
